### ISSUE TITLE
chat_n_radio.dds

### ISSUE THREAD

**Issue by Multisoft1978** [IDDQD1337/CSO2-Russian-Localization#1]
Проблема с данным файлом, игра вылетает.
Версия v24406 от 7 августа 2022
Есть ещё косяк с словом ПОБЕДА, и в результате того что данный файл не работает,
то слово отображается так: ПО Б**N**

**Comment by IDDQD1337** [comment]
У меня с этим вроде как такой проблемы нет, возможно у вас оказался битый файл

**Comment by Multisoft1978** [comment]
> У меня с этим вроде как такой проблемы нет, возможно у вас оказался битый файл

Распаковал из архива, так же скачивал отдельно с гитхаба, и перевод от пробовал WinKiller'а, везде проблема с этим файлом.
Сам файл в просмотре открывается без проблем, но когда добавляю его в игру игра вылетает.
А так же разный размер, цвет букв и расстояние между ними.
https://i.ibb.co/sFgDRDM/lol.png 

Кстати с result_003.png.dds тоже не загружается.
И созданный bat файл с прописанными логином и паролем запускают сам лаунчер, а не игру.
Ещё одну проблему нашёл, вылетает в игровой зоне. Не стал искать какой файл, вернул стоковые всё работает.

**Comment by IDDQD1337** [comment]
> Распаковал из архива, так же скачивал отдельно с гитхаба, и перевод от пробовал WinKiller'а, везде проблема с этим файлом. Сам файл в просмотре открывается без проблем, но когда добавляю его в игру игра вылетает. А так же разный размер, цвет букв и расстояние между ними. https://i.ibb.co/sFgDRDM/lol.png
> 
> Кстати с result_003.png.dds тоже не загружается. И созданный bat файл с прописанными логином и паролем запускают сам лаунчер, а не игру. Ещё одну проблему нашёл, вылетает в игровой зоне. Не стал искать какой файл, вернул стоковые всё работает.

1. К сожалению я не идеален в размерах и цвет букв, насчёт расстояния тут другая причина W I N разделены на три части, в отличии от LOSE и несколько других слов. В принципе это можно исправить.

2. Как я уже описал выше у меня таких проблем нет, но так как у вас файл открывается идеально и без проблем, возможно у вас проблема с игрой или чем-то ещё!

**Comment by Multisoft1978** [comment]
Я уже два раза игру переустанавливал.
Всё равно то же самое.
Так что тут видимо какая-то другая причина.
Надо смотреть версию игры.
Игра проверяет наличие файлов и их контрольную сумму но не у всех файлов.
Игру качал от сюда cso2.wohlnet.ru/ru

**Comment by Multisoft1978** [comment]
Дело ещё вот в чём, я заменял файлы в самой игре: Counter-Strike Online 2 Global\Data\cstrike\ui_gfx
Я так понимаю папка custom с локализацией должна быть в корне папки с игрой, но если создать bat файл и прописать в него:
start launcher.exe  -lang russian -masterip global -decryptedfiles -enablecustom -login мой логин -password мой пароль
Ничего не происходит.
А если прописать:
CounterStrikeOnline2.exe -lang russian -masterip global -decryptedfiles -enablecustom -login мой логин -password мой пароль
Запускается заставка с игрой, далее проверяется версия клиента и выдаёт ошибку на корейском.
Не удалось подключиться к counter strike online 2 i patcher server.
Пожалуйста повторите попытку позже.

В папке создаётся лог файл:

10:36:43	2023-03-27  Rev : 24406
10:36:43	NMStage[101] - main function started
10:36:43	ExecuteCount:0
10:36:43	NMStage[102] - 
10:36:43	NMStage[103] - 
10:36:43	Start Process [ HDD: 260.43/731.51 | 26.59/199.39 (0)]
10:36:43	League=0
10:36:43	NMStage[104] - 
10:36:43	Init Process #10
10:36:43	Init Process #20
10:36:43	Init Process ##10
10:36:43	Init Process ##20
10:36:43	Init FS ###00
10:36:43	Init FS ###10
10:36:43	D:/Games\Counter-Strike Online 2 Global\Data\1b87c6b551e518d11114ee21b7645a47.pkg is not exist. [Error:2]
10:36:43	Не удается найти указанный файл.

10:36:43	Init Process ##30
10:36:43	Init Process ##40
10:36:43	Init Process ##50
10:37:23	Init Process ##60
10:38:52	NMStage[105] - 
10:38:52	Init Process #30

Если запускать игру через cso2_global_launcher.exe то по всей видимости игнорируется папка custom, и перевода вовсе нет.
По всей видимости в игре должны быть файлы pkg но у меня уже похоже распакованная и раскриптованная версия.

**Comment by IDDQD1337** [comment]
1. Вы попробовали запустить launcher.exe от имени администратора?
2. CounterStrikeOnline2.exe на данный момент бесполезный файл
